version: "3.9"
services:
  order-service:
    image: order-service
    container_name: order-service
    ports:
      - "20000:20000"
    links:
      - payment-service
  payment-service:
    image: payment-service
    container_name: payment-service
    ports:
      - "20001:20001"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"


