server:
  port: 20000
resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        sliding-window-type: count_based # also time_based possibility
        sliding-window-size: 10
        failure-rate-threshold: 50 # percent
        wait-duration-in-open-state: 40s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-rate-threshold: 50 # percent
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        register-health-indicator: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true

payment-service-url: http://payment-service:20001/transactions
